# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'WeiBoExercise' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WeiBoExercise

  target 'WeiBoExerciseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WeiBoExerciseUITests' do
    inherit! :search_paths
    # Pods for testing
  end

pod “AFNetworking”
pod “SDWebImage”
pod “SVProgressHUD”

end
